services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crawl_db
    ports:
      - '6000:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:6000/crawl_db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: bash -c "npm run start:dev" # Sử dụng bash để chạy lệnh
volumes:
  postgres_data:
